# Test 3: Impulse Suppressor ONLY
# ============================
# Purpose: Check if Impulse Suppressor is too aggressive

audio:
  sample_rate: 16000
  chunk_size: 1024
  channels: 1
  format: float32

filters:
  # Stage 1: High-pass Filter
  highpass:
    enabled: false  # ❌ DISABLED

  # Stage 2: Impulse Noise Suppressor
  impulse_suppressor:
    enabled: true   # ✅ ENABLED (ONLY THIS)
    threshold_factor: 3.0
    window_size: 5

  # Stage 3: AI Denoiser
  ai_denoiser:
    enabled: false  # ❌ DISABLED
    model_path: null
    device: cpu

  # Stage 4: Soft Limiter
  limiter:
    enabled: false  # ❌ DISABLED

performance:
  buffer_size: 4096
  num_threads: 1
  realtime_priority: false
