# RP5-A Configuration for WiFi Direct Full-Duplex Communication
# Network: WiFi Direct (RP5-Direct)
# RP5-A acts as Access Point (10.42.0.1)

role: A
peer_ip: 10.42.0.224
mic_device: 1
speaker_device: 1
send_port: 9999  # 9998 → 9999 (B의 recv_port로!)
recv_port: 9998  # 9999 → 9998 (B의 send_port에서!)
model: Light-32-Depth4